// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uphzuizwwtrgkylpbrfd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVwaHp1aXp3d3RyZ2t5bHBicmZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxMTg3NDcsImV4cCI6MjA2MjY5NDc0N30.7nnXco8nYiHMf62e6NkC7kcJ6yh0gNvjP5sgpPqiZkk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);